require "bundler/setup"
require "bundler/gem_tasks"
require "bump/tasks"

task :default do
  sh "rspec spec/"
end

task :update do
  require "open-uri"

  Dir["lib/maxitest/vendor/*"].each do |file|
    parts = File.read(file).split(%r{(# https://.*)})

    parts = [parts[0].strip] + parts[1..-1].each_slice(2).map do |url, section|
      do_not_modify = "generated by rake update, do not modify"
      code = open(url.sub("# ", "")).read.gsub(/require .*?\n/, "").strip
      code = "=begin\n#{code}\n=end" if url.include?("LICENSE")
      if url.include?("testrbl.rb")
        # nest under Maxitest to avoid collision
        code = "module Maxitest\n#{code.gsub(/^/, "  ").gsub(/^\s+$/, "")}\nend"
      elsif url.include?("line_plugin.rb")
        # add red failure lines -- https://github.com/judofyr/minitest-line/pull/5
        code.sub!(%{io.puts "ruby \#{file} -l \#{line}"}, %{output = "ruby \#{file} -l \#{line}"\n          output = "\\e[31m\#{output}\\e[0m" if $stdout.tty?\n          io.puts output})
      end

      "#{url}\n# BEGIN #{do_not_modify}\n#{code.strip}\n#END #{do_not_modify}"
    end

    File.write(file, parts.reject(&:empty?).join("\n\n"))
  end
end
